version: '3'

services:
  db:
    image: postgres:14-alpine3.17
    container_name: db_app
    user: postgres
    env_file: ./graduate2/.env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready' ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    image: app
    container_name: app_graduate
    depends_on:
      db:
        condition: service_healthy
    env_file: ./graduate2/.env
    ports:
      - "8000:8000"
    volumes:
      - ../:/config
    command: bash -c "
      python manage.py migrate
      && python manage.py create_users
      && python manage.py runserver 0.0.0.0:8000
      "