# Generated by Django 4.2.5 on 2023-09-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Post_title')),
                ('description', models.TextField(verbose_name='Post_description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/post/', verbose_name='Post_image')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
