# Generated by Django 4.2.5 on 2023-09-21 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpayment',
            old_name='paid',
            new_name='is_paid',
        ),
    ]
